In [ ]:
install.packages("NeuroDataSets")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(NeuroDataSets)

In [ ]:
data(ASD_risks_tbl_df)

In [ ]:
ASD_risks_tbl_df

     CASE_NO_PATIENT'S A1 A2 A3 A4 A5 A6 A7 A8 A9 ⋯
1     1                0  0  0  0  0  0  1  1  0  ⋯
2     2                1  1  0  0  0  1  1  0  0  ⋯
3     3                1  0  0  0  0  0  1  1  0  ⋯
4     4                1  1  1  1  1  1  1  1  1  ⋯
5     5                1  1  0  1  1  1  1  1  1  ⋯
6     6                1  1  0  0  1  1  1  1  1  ⋯
7     7                1  0  0  1  1  1  0  0  1  ⋯
8     8                0  1  0  0  1  0  1  1  1  ⋯
9     9                0  0  0  0  0  0  1  0  0  ⋯
10   10                1  1  1  0  1  1  0  1  1  ⋯
11   11                1  0  0  1  0  1  1  0  1  ⋯
12   12                1  1  1  1  0  1  1  1  0  ⋯
13   13                0  0  0  0  0  0  0  0  0  ⋯
14   14                1  1  1  1  0  0  1  0  1  ⋯
15   15                0  0  0  0  0  0  0  0  0  ⋯
16   16                1  1  1  0  1  0  1  1  0  ⋯
17   17                0  0  0  0  0  0  0  0  0  ⋯
18   18                1  1  1  0  1  1  1  1  0  ⋯
19   19                1  0  0  0  1  0  0  0  0  ⋯
20   20                1  1  1  0  1  0  1  1  0  ⋯
21   21                1  0  0  1  1  1  1  1  1  ⋯
22   22                1  0  1  1  1  1  1  0  1  ⋯
23   23                1  0  1  1  0  1  0  1  1  ⋯
24   24                1  1  1  0  1  1  0  1  1  ⋯
25   25                1  1  1  1  1  1  1  1  1  ⋯
26   26                0  0  0  0  0  0  0  0  0  ⋯
27   27                1  1  0  1  1  1  1  1  0  ⋯
28   28                1  1  1  1  1  1  1  1  1  ⋯
29   29                0  0  1  1  1  0  1  1  1  ⋯
30   30                0  0  0  0  0  0  0  0  0  ⋯
⋮    ⋮                 ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋱
1956 1956              0  0  0  0  0  0  0  0  0  ⋯
1957 1957              0  0  0  0  0  0  0  0  0  ⋯
1958 1958              0  0  0  0  0  0  0  0  0  ⋯
1959 1959              0  0  0  0  0  0  0  0  0  ⋯
1960 1960              0  0  0  0  0  0  0  0  0  ⋯
1961 1961              0  0  0  0  0  0  0  0  0  ⋯
1962 1962              0  0  0  0  0  0  0  0  0  ⋯
1963 1963              0  0  0  0  0  0  0  0  0  ⋯
1964 1964              0  0  0  0  0  0  0  0  0  ⋯
1965 1965              0  0  0  0  0  0  0  0  0  ⋯
1966 1966              0  0  0  0  0  0  0  0  0  ⋯
1967 1967              0  0  0  0  0  0  0  0  0  ⋯
1968 1968              0  0  0  0  0  0  0  0  0  ⋯
1969 1969              0  0  0  0  0  0  0  0  0  ⋯
1970 1970              0  0  0  0  0  0  0  0  0  ⋯
1971 1971              0  0  0  0  0  0  0  0  0  ⋯
1972 1972              0  0  0  0  0  0  0  0  0  ⋯
1973 1973              0  0  0  0  0  0  0  0  0  ⋯
1974 1974              0  0  0  0  0  0  0  0  0  ⋯
1975 1975              0  0  0  0  0  0  0  0  0  ⋯
1976 1976              0  0  0  0  0  0  0  0  0  ⋯
1977 1977              0  0  0  0  0  0  0  0  0  ⋯
1978 1978              0  0  0  0  0  0  0  0  0  ⋯
1979 1979              0  0  0  0  0  0  0  0  0  ⋯
1980 1980              0  0  0  0  0  0  0  0  0  ⋯
1981 1981              0  0  0  0  0  0  0  0  0  ⋯
1982 1982              0  0  0  0  0  0  0  0  0  ⋯
1983 1983              0  0  0  0  0  0  0  0  0  ⋯
1984 1984              0  0  0  0  0  0  0  0  0  ⋯
1985 1985              0  0  0  0  0  0  0  0  0  ⋯
     Global developmental delay/intellectual disability
1    Yes
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
10   Yes
11   Yes
12   Yes
13   Yes
14   Yes
15   Yes
16   Yes
17   Yes
18   Yes
19   Yes
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   Yes
27   Yes
28   Yes
29   Yes
30   Yes
⋮    ⋮
1956 No
1957 No
1958 No
1959 No
1960 No
1961 No
1962 No
1963 No
1964 No
1965 No
1966 No
1967 No
1968 No
1969 No
1970 No
1971 No
1972 No
1973 No
1974 No
1975 No
1976 No
1977 No
1978 No
1979 No
1980 No
1981 No
1982 No
1983 No
1984 No
1985 No
     Social/Behavioural Issues Childhood Autism Rating Scale Anxiety_disorder
1    Yes                       1                             Yes
2    Yes                       2                             Yes
3    Yes                       4                             Yes
4    Yes                       2                             Yes
5    Yes                       1                             Yes
6    Yes                       2                             Yes
7    Yes                       4                             Yes
8    Yes                       2                             Yes
9    Yes                       2                             Yes
10   Yes                       1                             Yes
11   Yes                       4                             Yes
12   Yes                       2                             Yes
13   Yes                       1                             Yes
14   Yes                       2                             Yes
15   Yes                       4                             Yes
16   Yes                       2                             Yes
17   Yes                       2                             Yes
18   Yes                       1                             Yes
19   Yes                       4                             Yes
20   Yes                       2                             Yes
21   Yes                       1                             Yes
22   Yes                       2                             Yes
23   Yes                       4                             Yes
24   Yes                       2                             Yes
25   Yes                       2                             Yes
26   Yes                       1                             Yes
27   Yes                       4                             Yes
28   Yes                       2                             Yes
29   Yes                       1                             Yes
30   Yes                       2                             Yes
⋮    ⋮                         ⋮                             ⋮
1956 No                        1                             No
1957 No                        1                             No
1958 No                        1                             No
1959 No                        1                             No
1960 No                        1                             No
1961 No                        1                             No
1962 No                        1                             No
1963 No                        1                             No
1964 No                        1                             No
1965 No                        1                             No
1966 No                        1                             No
1967 No                        1                             No
1968 No                        1                             No
1969 No                        1                             No
1970 No                        1                             No
1971 No                        1                             No
1972 No                        1                             No
1973 No                        1                             No
1974 No                        1                             No
1975 No                        1                             No
1976 No                        1                             No
1977 No                        1                             No
1978 No                        1                             No
1979 No                        1                             No
1980 No                        1                             No
1981 No                        1                             No
1982 No                        1                             No
1983 No                        1                             No
1984 No                        1                             No
1985 No                        1                             No
     Sex Ethnicity      Jaundice Family_mem_with_ASD Who_completed_the_test
1    F   middle eastern Yes      No                  Family Member
2    M   White European Yes      No                  Family Member
3    M   Middle Eastern Yes      No                  Family Member
4    M   Hispanic       No       No                  Family Member
5    F   White European No       No                  Family Member
6    M   Black          No       No                  Family Member
7    M   Asian          Yes      No                  Family Member
8    M   Asian          Yes      No                  Family Member
9    M   Asian          No       No                  Family Member
10   M   South Asian    No       No                  Health Care Professional
11   M   Hispanic       Yes      Yes                 Family Member
12   M   Middle Eastern Yes      No                  Family Member
13   F   Middle Eastern Yes      No                  Family Member
14   F   middle eastern Yes      No                  Family Member
15   M   Middle Eastern Yes      No                  Family Member
16   M   Black          Yes      No                  Family Member
17   M   Middle Eastern Yes      Yes                 Family Member
18   F   Middle Eastern Yes      No                  Family Member
19   F   Middle Eastern Yes      No                  Family Member
20   M   Black          Yes      No                  Family Member
21   M   Middle Eastern Yes      No                  Family Member
22   M   Middle Eastern Yes      No                  Family Member
23   M   Native Indian  Yes      Yes                 Health Care Professional
24   M   Middle Eastern Yes      Yes                 Family Member
25   M   White European Yes      No                  Family Member
26   M   Middle Eastern Yes      No                  Family Member
27   M   Middle Eastern Yes      No                  Family Member
28   M   Others         Yes      No                  Family Member
29   M   Middle Eastern Yes      Yes                 Family Member
30   M   Middle Eastern Yes      No                  Family Member
⋮    ⋮   ⋮              ⋮        ⋮                   ⋮
1956 M   Middle Eastern No       No                  Health Care Professional
1957 F   south asian    No       No                  Health Care Professional
1958 M   White European No       No                  Health Care Professional
1959 M   Middle Eastern No       No                  Health Care Professional
1960 M   Asian          No       Yes                 Health Care Professional
1961 M   White European No       No                  Health Care Professional
1962 M   Middle Eastern No       No                  Health Care Professional
1963 F   south asian    No       No                  Health Care Professional
1964 F   asian          No       No                  Health Care Professional
1965 M   Asian          No       Yes                 Health Care Professional
1966 M   White European No       No                  Health Care Professional
1967 M   Middle Eastern No       No                  Health Care Professional
1968 F   south asian    No       No                  Health Care Professional
1969 F   asian          No       No                  Health Care Professional
1970 M   White European No       No                  Health Care Professional
1971 M   Middle Eastern No       No                  Health Care Professional
1972 F   south asian    No       No                  Health Care Professional
1973 M   White European No       No                  Health Care Professional
1974 M   Middle Eastern No       No                  Health Care Professional
1975 M   Asian          No       Yes                 Health Care Professional
1976 M   White European No       No                  Health Care Professional
1977 M   Middle Eastern No       No                  Health Care Professional
1978 F   south asian    No       No                  Health Care Professional
1979 F   asian          No       No                  Health Care Professional
1980 M   White European No       No                  Health Care Professional
1981 M   Middle Eastern No       No                  Health Care Professional
1982 F   south asian    No       No                  Health Care Professional
1983 M   White European No       No                  Health Care Professional
1984 M   Middle Eastern No       No                  Health Care Professional
1985 M   White European No       No                  Health Care Professional
     ASD_traits
1    No
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    No
10   Yes
11   Yes
12   Yes
13   No
14   Yes
15   No
16   Yes
17   No
18   Yes
19   No
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   No
27   Yes
28   Yes
29   Yes
30   No
⋮    ⋮
1956 No
1957 No
1958 Yes
1959 No
1960 Yes
1961 Yes
1962 No
1963 No
1964 No
1965 Yes
1966 Yes
1967 No
1968 No
1969 No
1970 Yes
1971 No
1972 No
1973 Yes
1974 No
1975 Yes
1976 Yes
1977 No
1978 No
1979 No
1980 Yes
1981 No
1982 No
1983 Yes
1984 No
1985 Yes

In [ ]:
asd <- ASD_risks_tbl_df

In [ ]:
install.packages("janitor")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘snakecase’

In [ ]:
library(janitor)

Attaching package: ‘janitor’


The following objects are masked from ‘package:stats’:

    chisq.test, fisher.test

In [ ]:
asd_clean <- clean_names(asd)    # Add consistency in variable or column names
asd_clean

     case_no_patients a1 a2 a3 a4 a5 a6 a7 a8 a9 ⋯
1     1               0  0  0  0  0  0  1  1  0  ⋯
2     2               1  1  0  0  0  1  1  0  0  ⋯
3     3               1  0  0  0  0  0  1  1  0  ⋯
4     4               1  1  1  1  1  1  1  1  1  ⋯
5     5               1  1  0  1  1  1  1  1  1  ⋯
6     6               1  1  0  0  1  1  1  1  1  ⋯
7     7               1  0  0  1  1  1  0  0  1  ⋯
8     8               0  1  0  0  1  0  1  1  1  ⋯
9     9               0  0  0  0  0  0  1  0  0  ⋯
10   10               1  1  1  0  1  1  0  1  1  ⋯
11   11               1  0  0  1  0  1  1  0  1  ⋯
12   12               1  1  1  1  0  1  1  1  0  ⋯
13   13               0  0  0  0  0  0  0  0  0  ⋯
14   14               1  1  1  1  0  0  1  0  1  ⋯
15   15               0  0  0  0  0  0  0  0  0  ⋯
16   16               1  1  1  0  1  0  1  1  0  ⋯
17   17               0  0  0  0  0  0  0  0  0  ⋯
18   18               1  1  1  0  1  1  1  1  0  ⋯
19   19               1  0  0  0  1  0  0  0  0  ⋯
20   20               1  1  1  0  1  0  1  1  0  ⋯
21   21               1  0  0  1  1  1  1  1  1  ⋯
22   22               1  0  1  1  1  1  1  0  1  ⋯
23   23               1  0  1  1  0  1  0  1  1  ⋯
24   24               1  1  1  0  1  1  0  1  1  ⋯
25   25               1  1  1  1  1  1  1  1  1  ⋯
26   26               0  0  0  0  0  0  0  0  0  ⋯
27   27               1  1  0  1  1  1  1  1  0  ⋯
28   28               1  1  1  1  1  1  1  1  1  ⋯
29   29               0  0  1  1  1  0  1  1  1  ⋯
30   30               0  0  0  0  0  0  0  0  0  ⋯
⋮    ⋮                ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋱
1956 1956             0  0  0  0  0  0  0  0  0  ⋯
1957 1957             0  0  0  0  0  0  0  0  0  ⋯
1958 1958             0  0  0  0  0  0  0  0  0  ⋯
1959 1959             0  0  0  0  0  0  0  0  0  ⋯
1960 1960             0  0  0  0  0  0  0  0  0  ⋯
1961 1961             0  0  0  0  0  0  0  0  0  ⋯
1962 1962             0  0  0  0  0  0  0  0  0  ⋯
1963 1963             0  0  0  0  0  0  0  0  0  ⋯
1964 1964             0  0  0  0  0  0  0  0  0  ⋯
1965 1965             0  0  0  0  0  0  0  0  0  ⋯
1966 1966             0  0  0  0  0  0  0  0  0  ⋯
1967 1967             0  0  0  0  0  0  0  0  0  ⋯
1968 1968             0  0  0  0  0  0  0  0  0  ⋯
1969 1969             0  0  0  0  0  0  0  0  0  ⋯
1970 1970             0  0  0  0  0  0  0  0  0  ⋯
1971 1971             0  0  0  0  0  0  0  0  0  ⋯
1972 1972             0  0  0  0  0  0  0  0  0  ⋯
1973 1973             0  0  0  0  0  0  0  0  0  ⋯
1974 1974             0  0  0  0  0  0  0  0  0  ⋯
1975 1975             0  0  0  0  0  0  0  0  0  ⋯
1976 1976             0  0  0  0  0  0  0  0  0  ⋯
1977 1977             0  0  0  0  0  0  0  0  0  ⋯
1978 1978             0  0  0  0  0  0  0  0  0  ⋯
1979 1979             0  0  0  0  0  0  0  0  0  ⋯
1980 1980             0  0  0  0  0  0  0  0  0  ⋯
1981 1981             0  0  0  0  0  0  0  0  0  ⋯
1982 1982             0  0  0  0  0  0  0  0  0  ⋯
1983 1983             0  0  0  0  0  0  0  0  0  ⋯
1984 1984             0  0  0  0  0  0  0  0  0  ⋯
1985 1985             0  0  0  0  0  0  0  0  0  ⋯
     global_developmental_delay_intellectual_disability
1    Yes
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
10   Yes
11   Yes
12   Yes
13   Yes
14   Yes
15   Yes
16   Yes
17   Yes
18   Yes
19   Yes
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   Yes
27   Yes
28   Yes
29   Yes
30   Yes
⋮    ⋮
1956 No
1957 No
1958 No
1959 No
1960 No
1961 No
1962 No
1963 No
1964 No
1965 No
1966 No
1967 No
1968 No
1969 No
1970 No
1971 No
1972 No
1973 No
1974 No
1975 No
1976 No
1977 No
1978 No
1979 No
1980 No
1981 No
1982 No
1983 No
1984 No
1985 No
     social_behavioural_issues childhood_autism_rating_scale anxiety_disorder
1    Yes                       1                             Yes
2    Yes                       2                             Yes
3    Yes                       4                             Yes
4    Yes                       2                             Yes
5    Yes                       1                             Yes
6    Yes                       2                             Yes
7    Yes                       4                             Yes
8    Yes                       2                             Yes
9    Yes                       2                             Yes
10   Yes                       1                             Yes
11   Yes                       4                             Yes
12   Yes                       2                             Yes
13   Yes                       1                             Yes
14   Yes                       2                             Yes
15   Yes                       4                             Yes
16   Yes                       2                             Yes
17   Yes                       2                             Yes
18   Yes                       1                             Yes
19   Yes                       4                             Yes
20   Yes                       2                             Yes
21   Yes                       1                             Yes
22   Yes                       2                             Yes
23   Yes                       4                             Yes
24   Yes                       2                             Yes
25   Yes                       2                             Yes
26   Yes                       1                             Yes
27   Yes                       4                             Yes
28   Yes                       2                             Yes
29   Yes                       1                             Yes
30   Yes                       2                             Yes
⋮    ⋮                         ⋮                             ⋮
1956 No                        1                             No
1957 No                        1                             No
1958 No                        1                             No
1959 No                        1                             No
1960 No                        1                             No
1961 No                        1                             No
1962 No                        1                             No
1963 No                        1                             No
1964 No                        1                             No
1965 No                        1                             No
1966 No                        1                             No
1967 No                        1                             No
1968 No                        1                             No
1969 No                        1                             No
1970 No                        1                             No
1971 No                        1                             No
1972 No                        1                             No
1973 No                        1                             No
1974 No                        1                             No
1975 No                        1                             No
1976 No                        1                             No
1977 No                        1                             No
1978 No                        1                             No
1979 No                        1                             No
1980 No                        1                             No
1981 No                        1                             No
1982 No                        1                             No
1983 No                        1                             No
1984 No                        1                             No
1985 No                        1                             No
     sex ethnicity      jaundice family_mem_with_asd who_completed_the_test
1    F   middle eastern Yes      No                  Family Member
2    M   White European Yes      No                  Family Member
3    M   Middle Eastern Yes      No                  Family Member
4    M   Hispanic       No       No                  Family Member
5    F   White European No       No                  Family Member
6    M   Black          No       No                  Family Member
7    M   Asian          Yes      No                  Family Member
8    M   Asian          Yes      No                  Family Member
9    M   Asian          No       No                  Family Member
10   M   South Asian    No       No                  Health Care Professional
11   M   Hispanic       Yes      Yes                 Family Member
12   M   Middle Eastern Yes      No                  Family Member
13   F   Middle Eastern Yes      No                  Family Member
14   F   middle eastern Yes      No                  Family Member
15   M   Middle Eastern Yes      No                  Family Member
16   M   Black          Yes      No                  Family Member
17   M   Middle Eastern Yes      Yes                 Family Member
18   F   Middle Eastern Yes      No                  Family Member
19   F   Middle Eastern Yes      No                  Family Member
20   M   Black          Yes      No                  Family Member
21   M   Middle Eastern Yes      No                  Family Member
22   M   Middle Eastern Yes      No                  Family Member
23   M   Native Indian  Yes      Yes                 Health Care Professional
24   M   Middle Eastern Yes      Yes                 Family Member
25   M   White European Yes      No                  Family Member
26   M   Middle Eastern Yes      No                  Family Member
27   M   Middle Eastern Yes      No                  Family Member
28   M   Others         Yes      No                  Family Member
29   M   Middle Eastern Yes      Yes                 Family Member
30   M   Middle Eastern Yes      No                  Family Member
⋮    ⋮   ⋮              ⋮        ⋮                   ⋮
1956 M   Middle Eastern No       No                  Health Care Professional
1957 F   south asian    No       No                  Health Care Professional
1958 M   White European No       No                  Health Care Professional
1959 M   Middle Eastern No       No                  Health Care Professional
1960 M   Asian          No       Yes                 Health Care Professional
1961 M   White European No       No                  Health Care Professional
1962 M   Middle Eastern No       No                  Health Care Professional
1963 F   south asian    No       No                  Health Care Professional
1964 F   asian          No       No                  Health Care Professional
1965 M   Asian          No       Yes                 Health Care Professional
1966 M   White European No       No                  Health Care Professional
1967 M   Middle Eastern No       No                  Health Care Professional
1968 F   south asian    No       No                  Health Care Professional
1969 F   asian          No       No                  Health Care Professional
1970 M   White European No       No                  Health Care Professional
1971 M   Middle Eastern No       No                  Health Care Professional
1972 F   south asian    No       No                  Health Care Professional
1973 M   White European No       No                  Health Care Professional
1974 M   Middle Eastern No       No                  Health Care Professional
1975 M   Asian          No       Yes                 Health Care Professional
1976 M   White European No       No                  Health Care Professional
1977 M   Middle Eastern No       No                  Health Care Professional
1978 F   south asian    No       No                  Health Care Professional
1979 F   asian          No       No                  Health Care Professional
1980 M   White European No       No                  Health Care Professional
1981 M   Middle Eastern No       No                  Health Care Professional
1982 F   south asian    No       No                  Health Care Professional
1983 M   White European No       No                  Health Care Professional
1984 M   Middle Eastern No       No                  Health Care Professional
1985 M   White European No       No                  Health Care Professional
     asd_traits
1    No
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    No
10   Yes
11   Yes
12   Yes
13   No
14   Yes
15   No
16   Yes
17   No
18   Yes
19   No
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   No
27   Yes
28   Yes
29   Yes
30   No
⋮    ⋮
1956 No
1957 No
1958 Yes
1959 No
1960 Yes
1961 Yes
1962 No
1963 No
1964 No
1965 Yes
1966 Yes
1967 No
1968 No
1969 No
1970 Yes
1971 No
1972 No
1973 Yes
1974 No
1975 Yes
1976 Yes
1977 No
1978 No
1979 No
1980 Yes
1981 No
1982 No
1983 Yes
1984 No
1985 Yes

In [ ]:
install.packages("mice")   # only once
library(mice)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘rbibutils’, ‘Rdpack’, ‘minqa’, ‘nloptr’, ‘reformulas’, ‘ucminf’, ‘numDeriv’, ‘iterators’, ‘lme4’, ‘ordinal’, ‘foreach’, ‘shape’, ‘RcppEigen’, ‘pan’, ‘jomo’, ‘glmnet’, ‘mitml’



Attaching package: ‘mice’


The following object is masked from ‘package:stats’:

    filter


The following objects are masked from ‘package:base’:

    cbind, rbind

In [ ]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
install.packages("stringr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(stringr)

In [ ]:
asd_mice_0 <- asd_clean |>
  # 1. Lowercase, trim whitespace, and Title-Case all character variables to standardize categories under categorical columns
  mutate(across(
    where(is.character),
    ~ str_to_title(str_to_lower(str_trim(.x)))
  ))

In [ ]:
asd_mice <- asd_mice_0 %>%
  mutate(
    across(where(is.character), as.factor),
    across(
      c(a1:a9, a10_autism_spectrum_quotient),
      ~ factor(.x, levels = c(0, 1))
    )
  )

  asd_mice

     case_no_patients a1 a2 a3 a4 a5 a6 a7 a8 a9 ⋯
1     1               0  0  0  0  0  0  1  1  0  ⋯
2     2               1  1  0  0  0  1  1  0  0  ⋯
3     3               1  0  0  0  0  0  1  1  0  ⋯
4     4               1  1  1  1  1  1  1  1  1  ⋯
5     5               1  1  0  1  1  1  1  1  1  ⋯
6     6               1  1  0  0  1  1  1  1  1  ⋯
7     7               1  0  0  1  1  1  0  0  1  ⋯
8     8               0  1  0  0  1  0  1  1  1  ⋯
9     9               0  0  0  0  0  0  1  0  0  ⋯
10   10               1  1  1  0  1  1  0  1  1  ⋯
11   11               1  0  0  1  0  1  1  0  1  ⋯
12   12               1  1  1  1  0  1  1  1  0  ⋯
13   13               0  0  0  0  0  0  0  0  0  ⋯
14   14               1  1  1  1  0  0  1  0  1  ⋯
15   15               0  0  0  0  0  0  0  0  0  ⋯
16   16               1  1  1  0  1  0  1  1  0  ⋯
17   17               0  0  0  0  0  0  0  0  0  ⋯
18   18               1  1  1  0  1  1  1  1  0  ⋯
19   19               1  0  0  0  1  0  0  0  0  ⋯
20   20               1  1  1  0  1  0  1  1  0  ⋯
21   21               1  0  0  1  1  1  1  1  1  ⋯
22   22               1  0  1  1  1  1  1  0  1  ⋯
23   23               1  0  1  1  0  1  0  1  1  ⋯
24   24               1  1  1  0  1  1  0  1  1  ⋯
25   25               1  1  1  1  1  1  1  1  1  ⋯
26   26               0  0  0  0  0  0  0  0  0  ⋯
27   27               1  1  0  1  1  1  1  1  0  ⋯
28   28               1  1  1  1  1  1  1  1  1  ⋯
29   29               0  0  1  1  1  0  1  1  1  ⋯
30   30               0  0  0  0  0  0  0  0  0  ⋯
⋮    ⋮                ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋮  ⋱
1956 1956             0  0  0  0  0  0  0  0  0  ⋯
1957 1957             0  0  0  0  0  0  0  0  0  ⋯
1958 1958             0  0  0  0  0  0  0  0  0  ⋯
1959 1959             0  0  0  0  0  0  0  0  0  ⋯
1960 1960             0  0  0  0  0  0  0  0  0  ⋯
1961 1961             0  0  0  0  0  0  0  0  0  ⋯
1962 1962             0  0  0  0  0  0  0  0  0  ⋯
1963 1963             0  0  0  0  0  0  0  0  0  ⋯
1964 1964             0  0  0  0  0  0  0  0  0  ⋯
1965 1965             0  0  0  0  0  0  0  0  0  ⋯
1966 1966             0  0  0  0  0  0  0  0  0  ⋯
1967 1967             0  0  0  0  0  0  0  0  0  ⋯
1968 1968             0  0  0  0  0  0  0  0  0  ⋯
1969 1969             0  0  0  0  0  0  0  0  0  ⋯
1970 1970             0  0  0  0  0  0  0  0  0  ⋯
1971 1971             0  0  0  0  0  0  0  0  0  ⋯
1972 1972             0  0  0  0  0  0  0  0  0  ⋯
1973 1973             0  0  0  0  0  0  0  0  0  ⋯
1974 1974             0  0  0  0  0  0  0  0  0  ⋯
1975 1975             0  0  0  0  0  0  0  0  0  ⋯
1976 1976             0  0  0  0  0  0  0  0  0  ⋯
1977 1977             0  0  0  0  0  0  0  0  0  ⋯
1978 1978             0  0  0  0  0  0  0  0  0  ⋯
1979 1979             0  0  0  0  0  0  0  0  0  ⋯
1980 1980             0  0  0  0  0  0  0  0  0  ⋯
1981 1981             0  0  0  0  0  0  0  0  0  ⋯
1982 1982             0  0  0  0  0  0  0  0  0  ⋯
1983 1983             0  0  0  0  0  0  0  0  0  ⋯
1984 1984             0  0  0  0  0  0  0  0  0  ⋯
1985 1985             0  0  0  0  0  0  0  0  0  ⋯
     global_developmental_delay_intellectual_disability
1    Yes
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
10   Yes
11   Yes
12   Yes
13   Yes
14   Yes
15   Yes
16   Yes
17   Yes
18   Yes
19   Yes
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   Yes
27   Yes
28   Yes
29   Yes
30   Yes
⋮    ⋮
1956 No
1957 No
1958 No
1959 No
1960 No
1961 No
1962 No
1963 No
1964 No
1965 No
1966 No
1967 No
1968 No
1969 No
1970 No
1971 No
1972 No
1973 No
1974 No
1975 No
1976 No
1977 No
1978 No
1979 No
1980 No
1981 No
1982 No
1983 No
1984 No
1985 No
     social_behavioural_issues childhood_autism_rating_scale anxiety_disorder
1    Yes                       1                             Yes
2    Yes                       2                             Yes
3    Yes                       4                             Yes
4    Yes                       2                             Yes
5    Yes                       1                             Yes
6    Yes                       2                             Yes
7    Yes                       4                             Yes
8    Yes                       2                             Yes
9    Yes                       2                             Yes
10   Yes                       1                             Yes
11   Yes                       4                             Yes
12   Yes                       2                             Yes
13   Yes                       1                             Yes
14   Yes                       2                             Yes
15   Yes                       4                             Yes
16   Yes                       2                             Yes
17   Yes                       2                             Yes
18   Yes                       1                             Yes
19   Yes                       4                             Yes
20   Yes                       2                             Yes
21   Yes                       1                             Yes
22   Yes                       2                             Yes
23   Yes                       4                             Yes
24   Yes                       2                             Yes
25   Yes                       2                             Yes
26   Yes                       1                             Yes
27   Yes                       4                             Yes
28   Yes                       2                             Yes
29   Yes                       1                             Yes
30   Yes                       2                             Yes
⋮    ⋮                         ⋮                             ⋮
1956 No                        1                             No
1957 No                        1                             No
1958 No                        1                             No
1959 No                        1                             No
1960 No                        1                             No
1961 No                        1                             No
1962 No                        1                             No
1963 No                        1                             No
1964 No                        1                             No
1965 No                        1                             No
1966 No                        1                             No
1967 No                        1                             No
1968 No                        1                             No
1969 No                        1                             No
1970 No                        1                             No
1971 No                        1                             No
1972 No                        1                             No
1973 No                        1                             No
1974 No                        1                             No
1975 No                        1                             No
1976 No                        1                             No
1977 No                        1                             No
1978 No                        1                             No
1979 No                        1                             No
1980 No                        1                             No
1981 No                        1                             No
1982 No                        1                             No
1983 No                        1                             No
1984 No                        1                             No
1985 No                        1                             No
     sex ethnicity      jaundice family_mem_with_asd who_completed_the_test
1    F   Middle Eastern Yes      No                  Family Member
2    M   White European Yes      No                  Family Member
3    M   Middle Eastern Yes      No                  Family Member
4    M   Hispanic       No       No                  Family Member
5    F   White European No       No                  Family Member
6    M   Black          No       No                  Family Member
7    M   Asian          Yes      No                  Family Member
8    M   Asian          Yes      No                  Family Member
9    M   Asian          No       No                  Family Member
10   M   South Asian    No       No                  Health Care Professional
11   M   Hispanic       Yes      Yes                 Family Member
12   M   Middle Eastern Yes      No                  Family Member
13   F   Middle Eastern Yes      No                  Family Member
14   F   Middle Eastern Yes      No                  Family Member
15   M   Middle Eastern Yes      No                  Family Member
16   M   Black          Yes      No                  Family Member
17   M   Middle Eastern Yes      Yes                 Family Member
18   F   Middle Eastern Yes      No                  Family Member
19   F   Middle Eastern Yes      No                  Family Member
20   M   Black          Yes      No                  Family Member
21   M   Middle Eastern Yes      No                  Family Member
22   M   Middle Eastern Yes      No                  Family Member
23   M   Native Indian  Yes      Yes                 Health Care Professional
24   M   Middle Eastern Yes      Yes                 Family Member
25   M   White European Yes      No                  Family Member
26   M   Middle Eastern Yes      No                  Family Member
27   M   Middle Eastern Yes      No                  Family Member
28   M   Others         Yes      No                  Family Member
29   M   Middle Eastern Yes      Yes                 Family Member
30   M   Middle Eastern Yes      No                  Family Member
⋮    ⋮   ⋮              ⋮        ⋮                   ⋮
1956 M   Middle Eastern No       No                  Health Care Professional
1957 F   South Asian    No       No                  Health Care Professional
1958 M   White European No       No                  Health Care Professional
1959 M   Middle Eastern No       No                  Health Care Professional
1960 M   Asian          No       Yes                 Health Care Professional
1961 M   White European No       No                  Health Care Professional
1962 M   Middle Eastern No       No                  Health Care Professional
1963 F   South Asian    No       No                  Health Care Professional
1964 F   Asian          No       No                  Health Care Professional
1965 M   Asian          No       Yes                 Health Care Professional
1966 M   White European No       No                  Health Care Professional
1967 M   Middle Eastern No       No                  Health Care Professional
1968 F   South Asian    No       No                  Health Care Professional
1969 F   Asian          No       No                  Health Care Professional
1970 M   White European No       No                  Health Care Professional
1971 M   Middle Eastern No       No                  Health Care Professional
1972 F   South Asian    No       No                  Health Care Professional
1973 M   White European No       No                  Health Care Professional
1974 M   Middle Eastern No       No                  Health Care Professional
1975 M   Asian          No       Yes                 Health Care Professional
1976 M   White European No       No                  Health Care Professional
1977 M   Middle Eastern No       No                  Health Care Professional
1978 F   South Asian    No       No                  Health Care Professional
1979 F   Asian          No       No                  Health Care Professional
1980 M   White European No       No                  Health Care Professional
1981 M   Middle Eastern No       No                  Health Care Professional
1982 F   South Asian    No       No                  Health Care Professional
1983 M   White European No       No                  Health Care Professional
1984 M   Middle Eastern No       No                  Health Care Professional
1985 M   White European No       No                  Health Care Professional
     asd_traits
1    No
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    No
10   Yes
11   Yes
12   Yes
13   No
14   Yes
15   No
16   Yes
17   No
18   Yes
19   No
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   No
27   Yes
28   Yes
29   Yes
30   No
⋮    ⋮
1956 No
1957 No
1958 Yes
1959 No
1960 Yes
1961 Yes
1962 No
1963 No
1964 No
1965 Yes
1966 Yes
1967 No
1968 No
1969 No
1970 Yes
1971 No
1972 No
1973 Yes
1974 No
1975 Yes
1976 Yes
1977 No
1978 No
1979 No
1980 Yes
1981 No
1982 No
1983 Yes
1984 No
1985 Yes

In [ ]:
lapply(asd_mice[sapply(asd_mice, is.factor)], table, useNA = "ifany")

$a1

   0    1
1391  594

$a2

   0    1
1512  473

$a3

   0    1
1562  423

$a4

   0    1
1445  540

$a5

   0    1
1432  553

$a6

   0    1
1377  608

$a7

   0    1
1300  685

$a8

   0    1
1501  484

$a9

   0    1
1469  516

$a10_autism_spectrum_quotient

   0    1
1099  886

$speech_delay_language_disorder

  No  Yes
 928 1057

$learning_disorder

  No  Yes
 910 1075

$genetic_disorders

  No  Yes
 972 1013

$depression

  No  Yes <NA>
 930 1054    1

$global_developmental_delay_intellectual_disability

  No  Yes
 931 1054

$social_behavioural_issues

  No  Yes <NA>
 931 1040   14

$anxiety_disorder

  No  Yes
 934 1051

$sex

   F    M
 538 1447

$ethnicity

         Asian          Black       Hispanic         Latino Middle Eastern
           605             53             40             26            403
         Mixed  Native Indian         Others       Pacifica    South Asian
             8              3             35              8            255
White European
           549

$jaundice

  No  Yes
 449 1536

$family_mem_with_asd

  No  Yes
1330  655

$who_completed_the_test

           Family Member Health Care Professional                   Others
                     716                     1233                        3
          School And Ngo                     Self
                      29                        4

$asd_traits

  No  Yes
 911 1074

Standardized categories names obtained.

In [ ]:
str(asd_mice)

spc_tbl_ [1,985 × 28] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ case_no_patients                                  : num [1:1985] 1 2 3 4 5 6 7 8 9 10 ...
 $ a1                                                : Factor w/ 2 levels "0","1": 1 2 2 2 2 2 2 1 1 2 ...
 $ a2                                                : Factor w/ 2 levels "0","1": 1 2 1 2 2 2 1 2 1 2 ...
 $ a3                                                : Factor w/ 2 levels "0","1": 1 1 1 2 1 1 1 1 1 2 ...
 $ a4                                                : Factor w/ 2 levels "0","1": 1 1 1 2 2 1 2 1 1 1 ...
 $ a5                                                : Factor w/ 2 levels "0","1": 1 1 1 2 2 2 2 2 1 2 ...
 $ a6                                                : Factor w/ 2 levels "0","1": 1 2 1 2 2 2 2 1 1 2 ...
 $ a7                                                : Factor w/ 2 levels "0","1": 2 2 2 2 2 2 1 2 2 1 ...
 $ a8                                                : Factor w/ 2 levels "0","1": 2 1 2 2 2 2 1 2 1 2 ...
 $ a9                                                : Factor w/ 2 levels "0","1": 1 1 1 2 2 2 2 2 1 2 ...
 $ a10_autism_spectrum_quotient                      : Factor w/ 2 levels "0","1": 2 1 2 2 2 2 1 2 2 2 ...
 $ social_responsiveness_scale                       : num [1:1985] 3 6 7 1 3 3 3 3 5 6 ...
 $ age_years                                         : num [1:1985] 2 3 3 2 2 2 3 3 3 2 ...
 $ qchat_10_score                                    : num [1:1985] 3 4 4 10 9 8 5 6 2 8 ...
 $ speech_delay_language_disorder                    : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ learning_disorder                                 : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ genetic_disorders                                 : Factor w/ 2 levels "No","Yes": 2 2 2 1 1 1 2 2 1 1 ...
 $ depression                                        : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ global_developmental_delay_intellectual_disability: Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ social_behavioural_issues                         : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ childhood_autism_rating_scale                     : num [1:1985] 1 2 4 2 1 2 4 2 2 1 ...
 $ anxiety_disorder                                  : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ sex                                               : Factor w/ 2 levels "F","M": 1 2 2 2 1 2 2 2 2 2 ...
 $ ethnicity                                         : Factor w/ 11 levels "Asian","Black",..: 5 11 5 3 11 2 1 1 1 10 ...
 $ jaundice                                          : Factor w/ 2 levels "No","Yes": 2 2 2 1 1 1 2 2 1 1 ...
 $ family_mem_with_asd                               : Factor w/ 2 levels "No","Yes": 1 1 1 1 1 1 1 1 1 1 ...
 $ who_completed_the_test                            : Factor w/ 5 levels "Family Member",..: 1 1 1 1 1 1 1 1 1 2 ...
 $ asd_traits                                        : Factor w/ 2 levels "No","Yes": 1 2 2 2 2 2 2 2 1 2 ...
 - attr(*, "spec")=List of 3
  ..$ cols   :List of 28
  .. ..$ CASE_NO_PATIENT'S                                 : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A1                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A2                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A3                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A4                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A5                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A6                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A7                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A8                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A9                                                : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ A10_Autism_Spectrum_Quotient                      : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ Social_Responsiveness_Scale                       : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ Age_Years                                         : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ Qchat_10_Score                                    : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ Speech Delay/Language Disorder                    : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Learning disorder                                 : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Genetic_Disorders                                 : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Depression                                        : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Global developmental delay/intellectual disability: list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Social/Behavioural Issues                         : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Childhood Autism Rating Scale                     : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"
  .. ..$ Anxiety_disorder                                  : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Sex                                               : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Ethnicity                                         : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Jaundice                                          : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Family_mem_with_ASD                               : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ Who_completed_the_test                            : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  .. ..$ ASD_traits                                        : list()
  .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
  ..$ default: list()
  .. ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"
  ..$ delim  : chr ","
  ..- attr(*, "class")= chr "col_spec"
 - attr(*, "problems")=<pointer: (nil)>

In [ ]:
ini <- mice(asd_mice, maxit = 0)

ini$method

Warning message:
“Number of logged events: 1”

                                  case_no_patients
                                                ""
                                                a1
                                                ""
                                                a2
                                                ""
                                                a3
                                                ""
                                                a4
                                                ""
                                                a5
                                                ""
                                                a6
                                                ""
                                                a7
                                                ""
                                                a8
                                                ""
                                                a9
                                                ""
                      a10_autism_spectrum_quotient
                                                ""
                       social_responsiveness_scale
                                             "pmm"
                                         age_years
                                                ""
                                    qchat_10_score
                                             "pmm"
                    speech_delay_language_disorder
                                                ""
                                 learning_disorder
                                                ""
                                 genetic_disorders
                                                ""
                                        depression
                                          "logreg"
global_developmental_delay_intellectual_disability
                                                ""
                         social_behavioural_issues
                                                ""
                     childhood_autism_rating_scale
                                                ""
                                  anxiety_disorder
                                                ""
                                               sex
                                                ""
                                         ethnicity
                                                ""
                                          jaundice
                                                ""
                               family_mem_with_asd
                                                ""
                            who_completed_the_test
                                                ""
                                        asd_traits
                                                ""

social_behavioural_issues, even though missing are not assigned a method.

In [ ]:
class(asd_mice$social_behavioural_issues)

table(asd_mice$social_behavioural_issues, useNA = "ifany")

[1] "factor"

  No  Yes <NA>
 931 1040   14

It is indeed a factor with missing variables.

In [ ]:
ini$loggedEvents

  it im dep meth      out
1 0  0      collinear social_behavioural_issues

It turns out to be collinear.

In [ ]:
pred <- ini$predictorMatrix

pred["social_behavioural_issues", ]

                                  case_no_patients
                                                 0
                                                a1
                                                 0
                                                a2
                                                 0
                                                a3
                                                 0
                                                a4
                                                 0
                                                a5
                                                 0
                                                a6
                                                 0
                                                a7
                                                 0
                                                a8
                                                 0
                                                a9
                                                 0
                      a10_autism_spectrum_quotient
                                                 0
                       social_responsiveness_scale
                                                 0
                                         age_years
                                                 0
                                    qchat_10_score
                                                 0
                    speech_delay_language_disorder
                                                 0
                                 learning_disorder
                                                 0
                                 genetic_disorders
                                                 0
                                        depression
                                                 0
global_developmental_delay_intellectual_disability
                                                 0
                         social_behavioural_issues
                                                 0
                     childhood_autism_rating_scale
                                                 0
                                  anxiety_disorder
                                                 0
                                               sex
                                                 0
                                         ethnicity
                                                 0
                                          jaundice
                                                 0
                               family_mem_with_asd
                                                 0
                            who_completed_the_test
                                                 0
                                        asd_traits
                                                 0

For all other variables, social_behavioral_issues are dropped.

In [ ]:
pred

                                                   case_no_patients a1 a2 a3 a4
case_no_patients                                   0                1  1  1  1
a1                                                 1                0  1  1  1
a2                                                 1                1  0  1  1
a3                                                 1                1  1  0  1
a4                                                 1                1  1  1  0
a5                                                 1                1  1  1  1
a6                                                 1                1  1  1  1
a7                                                 1                1  1  1  1
a8                                                 1                1  1  1  1
a9                                                 1                1  1  1  1
a10_autism_spectrum_quotient                       1                1  1  1  1
social_responsiveness_scale                        1                1  1  1  1
age_years                                          1                1  1  1  1
qchat_10_score                                     1                1  1  1  1
speech_delay_language_disorder                     1                1  1  1  1
learning_disorder                                  1                1  1  1  1
genetic_disorders                                  1                1  1  1  1
depression                                         1                1  1  1  1
global_developmental_delay_intellectual_disability 1                1  1  1  1
social_behavioural_issues                          0                0  0  0  0
childhood_autism_rating_scale                      1                1  1  1  1
anxiety_disorder                                   1                1  1  1  1
sex                                                1                1  1  1  1
ethnicity                                          1                1  1  1  1
jaundice                                           1                1  1  1  1
family_mem_with_asd                                1                1  1  1  1
who_completed_the_test                             1                1  1  1  1
asd_traits                                         1                1  1  1  1
                                                   a5 a6 a7 a8 a9 ⋯
case_no_patients                                   1  1  1  1  1  ⋯
a1                                                 1  1  1  1  1  ⋯
a2                                                 1  1  1  1  1  ⋯
a3                                                 1  1  1  1  1  ⋯
a4                                                 1  1  1  1  1  ⋯
a5                                                 0  1  1  1  1  ⋯
a6                                                 1  0  1  1  1  ⋯
a7                                                 1  1  0  1  1  ⋯
a8                                                 1  1  1  0  1  ⋯
a9                                                 1  1  1  1  0  ⋯
a10_autism_spectrum_quotient                       1  1  1  1  1  ⋯
social_responsiveness_scale                        1  1  1  1  1  ⋯
age_years                                          1  1  1  1  1  ⋯
qchat_10_score                                     1  1  1  1  1  ⋯
speech_delay_language_disorder                     1  1  1  1  1  ⋯
learning_disorder                                  1  1  1  1  1  ⋯
genetic_disorders                                  1  1  1  1  1  ⋯
depression                                         1  1  1  1  1  ⋯
global_developmental_delay_intellectual_disability 1  1  1  1  1  ⋯
social_behavioural_issues                          0  0  0  0  0  ⋯
childhood_autism_rating_scale                      1  1  1  1  1  ⋯
anxiety_disorder                                   1  1  1  1  1  ⋯
sex                                                1  1  1  1  1  ⋯
ethnicity                                          1  1  1  1  1  ⋯
jaundice                                           1  1  1  1  1  ⋯
family_mem_with_asd                                1  1  1  1  1  ⋯
who_completed_the_test                             1  1  1  1  1  ⋯
asd_traits                                         1  1  1  1  1  ⋯
                                                   global_developmental_delay_intellectual_disability
case_no_patients                                   1
a1                                                 1
a2                                                 1
a3                                                 1
a4                                                 1
a5                                                 1
a6                                                 1
a7                                                 1
a8                                                 1
a9                                                 1
a10_autism_spectrum_quotient                       1
social_responsiveness_scale                        1
age_years                                          1
qchat_10_score                                     1
speech_delay_language_disorder                     1
learning_disorder                                  1
genetic_disorders                                  1
depression                                         1
global_developmental_delay_intellectual_disability 0
social_behavioural_issues                          0
childhood_autism_rating_scale                      1
anxiety_disorder                                   1
sex                                                1
ethnicity                                          1
jaundice                                           1
family_mem_with_asd                                1
who_completed_the_test                             1
asd_traits                                         1
                                                   social_behavioural_issues
case_no_patients                                   0
a1                                                 0
a2                                                 0
a3                                                 0
a4                                                 0
a5                                                 0
a6                                                 0
a7                                                 0
a8                                                 0
a9                                                 0
a10_autism_spectrum_quotient                       0
social_responsiveness_scale                        0
age_years                                          0
qchat_10_score                                     0
speech_delay_language_disorder                     0
learning_disorder                                  0
genetic_disorders                                  0
depression                                         0
global_developmental_delay_intellectual_disability 0
social_behavioural_issues                          0
childhood_autism_rating_scale                      0
anxiety_disorder                                   0
sex                                                0
ethnicity                                          0
jaundice                                           0
family_mem_with_asd                                0
who_completed_the_test                             0
asd_traits                                         0
                                                   childhood_autism_rating_scale
case_no_patients                                   1
a1                                                 1
a2                                                 1
a3                                                 1
a4                                                 1
a5                                                 1
a6                                                 1
a7                                                 1
a8                                                 1
a9                                                 1
a10_autism_spectrum_quotient                       1
social_responsiveness_scale                        1
age_years                                          1
qchat_10_score                                     1
speech_delay_language_disorder                     1
learning_disorder                                  1
genetic_disorders                                  1
depression                                         1
global_developmental_delay_intellectual_disability 1
social_behavioural_issues                          0
childhood_autism_rating_scale                      0
anxiety_disorder                                   1
sex                                                1
ethnicity                                          1
jaundice                                           1
family_mem_with_asd                                1
who_completed_the_test                             1
asd_traits                                         1
                                                   anxiety_disorder sex
case_no_patients                                   1                1
a1                                                 1                1
a2                                                 1                1
a3                                                 1                1
a4                                                 1                1
a5                                                 1                1
a6                                                 1                1
a7                                                 1                1
a8                                                 1                1
a9                                                 1                1
a10_autism_spectrum_quotient                       1                1
social_responsiveness_scale                        1                1
age_years                                          1                1
qchat_10_score                                     1                1
speech_delay_language_disorder                     1                1
learning_disorder                                  1                1
genetic_disorders                                  1                1
depression                                         1                1
global_developmental_delay_intellectual_disability 1                1
social_behavioural_issues                          0                0
childhood_autism_rating_scale                      1                1
anxiety_disorder                                   0                1
sex                                                1                0
ethnicity                                          1                1
jaundice                                           1                1
family_mem_with_asd                                1                1
who_completed_the_test                             1                1
asd_traits                                         1                1
                                                   ethnicity jaundice
case_no_patients                                   1         1
a1                                                 1         1
a2                                                 1         1
a3                                                 1         1
a4                                                 1         1
a5                                                 1         1
a6                                                 1         1
a7                                                 1         1
a8                                                 1         1
a9                                                 1         1
a10_autism_spectrum_quotient                       1         1
social_responsiveness_scale                        1         1
age_years                                          1         1
qchat_10_score                                     1         1
speech_delay_language_disorder                     1         1
learning_disorder                                  1         1
genetic_disorders                                  1         1
depression                                         1         1
global_developmental_delay_intellectual_disability 1         1
social_behavioural_issues                          0         0
childhood_autism_rating_scale                      1         1
anxiety_disorder                                   1         1
sex                                                1         1
ethnicity                                          0         1
jaundice                                           1         0
family_mem_with_asd                                1         1
who_completed_the_test                             1         1
asd_traits                                         1         1
                                                   family_mem_with_asd
case_no_patients                                   1
a1                                                 1
a2                                                 1
a3                                                 1
a4                                                 1
a5                                                 1
a6                                                 1
a7                                                 1
a8                                                 1
a9                                                 1
a10_autism_spectrum_quotient                       1
social_responsiveness_scale                        1
age_years                                          1
qchat_10_score                                     1
speech_delay_language_disorder                     1
learning_disorder                                  1
genetic_disorders                                  1
depression                                         1
global_developmental_delay_intellectual_disability 1
social_behavioural_issues                          0
childhood_autism_rating_scale                      1
anxiety_disorder                                   1
sex                                                1
ethnicity                                          1
jaundice                                           1
family_mem_with_asd                                0
who_completed_the_test                             1
asd_traits                                         1
                                                   who_completed_the_test
case_no_patients                                   1
a1                                                 1
a2                                                 1
a3                                                 1
a4                                                 1
a5                                                 1
a6                                                 1
a7                                                 1
a8                                                 1
a9                                                 1
a10_autism_spectrum_quotient                       1
social_responsiveness_scale                        1
age_years                                          1
qchat_10_score                                     1
speech_delay_language_disorder                     1
learning_disorder                                  1
genetic_disorders                                  1
depression                                         1
global_developmental_delay_intellectual_disability 1
social_behavioural_issues                          0
childhood_autism_rating_scale                      1
anxiety_disorder                                   1
sex                                                1
ethnicity                                          1
jaundice                                           1
family_mem_with_asd                                1
who_completed_the_test                             0
asd_traits                                         1
                                                   asd_traits
case_no_patients                                   1
a1                                                 1
a2                                                 1
a3                                                 1
a4                                                 1
a5                                                 1
a6                                                 1
a7                                                 1
a8                                                 1
a9                                                 1
a10_autism_spectrum_quotient                       1
social_responsiveness_scale                        1
age_years                                          1
qchat_10_score                                     1
speech_delay_language_disorder                     1
learning_disorder                                  1
genetic_disorders                                  1
depression                                         1
global_developmental_delay_intellectual_disability 1
social_behavioural_issues                          0
childhood_autism_rating_scale                      1
anxiety_disorder                                   1
sex                                                1
ethnicity                                          1
jaundice                                           1
family_mem_with_asd                                1
who_completed_the_test                             1
asd_traits                                         0

In [ ]:
pred[c(
  "qchat_10_score",
  "social_responsiveness_scale",
  "depression",
  "social_behavioural_issues"
), ]

                            case_no_patients a1 a2 a3 a4 a5 a6 a7 a8 a9 ⋯
qchat_10_score              1                1  1  1  1  1  1  1  1  1  ⋯
social_responsiveness_scale 1                1  1  1  1  1  1  1  1  1  ⋯
depression                  1                1  1  1  1  1  1  1  1  1  ⋯
social_behavioural_issues   0                0  0  0  0  0  0  0  0  0  ⋯
                            global_developmental_delay_intellectual_disability
qchat_10_score              1
social_responsiveness_scale 1
depression                  1
social_behavioural_issues   0
                            social_behavioural_issues
qchat_10_score              0
social_responsiveness_scale 0
depression                  0
social_behavioural_issues   0
                            childhood_autism_rating_scale anxiety_disorder sex
qchat_10_score              1                             1                1
social_responsiveness_scale 1                             1                1
depression                  1                             1                1
social_behavioural_issues   0                             0                0
                            ethnicity jaundice family_mem_with_asd
qchat_10_score              1         1        1
social_responsiveness_scale 1         1        1
depression                  1         1        1
social_behavioural_issues   0         0        0
                            who_completed_the_test asd_traits
qchat_10_score              1                      1
social_responsiveness_scale 1                      1
depression                  1                      1
social_behavioural_issues   0                      0

In [ ]:
pred0 <- make.predictorMatrix(asd_mice)

pred0["social_behavioural_issues", ]

                                  case_no_patients
                                                 1
                                                a1
                                                 1
                                                a2
                                                 1
                                                a3
                                                 1
                                                a4
                                                 1
                                                a5
                                                 1
                                                a6
                                                 1
                                                a7
                                                 1
                                                a8
                                                 1
                                                a9
                                                 1
                      a10_autism_spectrum_quotient
                                                 1
                       social_responsiveness_scale
                                                 1
                                         age_years
                                                 1
                                    qchat_10_score
                                                 1
                    speech_delay_language_disorder
                                                 1
                                 learning_disorder
                                                 1
                                 genetic_disorders
                                                 1
                                        depression
                                                 1
global_developmental_delay_intellectual_disability
                                                 1
                         social_behavioural_issues
                                                 0
                     childhood_autism_rating_scale
                                                 1
                                  anxiety_disorder
                                                 1
                                               sex
                                                 1
                                         ethnicity
                                                 1
                                          jaundice
                                                 1
                               family_mem_with_asd
                                                 1
                            who_completed_the_test
                                                 1
                                        asd_traits
                                                 1

In the initial matrix, it was not dropped for other variables but after collinearity was found, it was.

In [ ]:
vars_to_check <- c(
  "speech_delay_language_disorder",
  "learning_disorder",
  "genetic_disorders",
  "depression",
  "global_developmental_delay_intellectual_disability",
  "anxiety_disorder",
  "sex",
  "jaundice",
  "family_mem_with_asd",
  "asd_traits"
)

lapply(
  vars_to_check,
  function(v) {
    list(
      variable = v,
      table = table(
        asd_mice$social_behavioural_issues,
        asd_mice[[v]],
        useNA = "ifany"
      )
    )
  }
)

[[1]]
[[1]]$variable
[1] "speech_delay_language_disorder"

[[1]]$table

         No  Yes
  No    928    3
  Yes     0 1040
  <NA>    0   14


[[2]]
[[2]]$variable
[1] "learning_disorder"

[[2]]$table

         No  Yes
  No    910   21
  Yes     0 1040
  <NA>    0   14


[[3]]
[[3]]$variable
[1] "genetic_disorders"

[[3]]$table

        No Yes
  No   931   0
  Yes   41 999
  <NA>   0  14


[[4]]
[[4]]$variable
[1] "depression"

[[4]]$table

         No  Yes <NA>
  No    930    0    1
  Yes     0 1040    0
  <NA>    0   14    0


[[5]]
[[5]]$variable
[1] "global_developmental_delay_intellectual_disability"

[[5]]$table

         No  Yes
  No    930    1
  Yes     1 1039
  <NA>    0   14


[[6]]
[[6]]$variable
[1] "anxiety_disorder"

[[6]]$table

         No  Yes
  No    931    0
  Yes     3 1037
  <NA>    0   14


[[7]]
[[7]]$variable
[1] "sex"

[[7]]$table

         F   M
  No   370 561
  Yes  165 875
  <NA>   3  11


[[8]]
[[8]]$variable
[1] "jaundice"

[[8]]$table

         No  Yes
  No    423  508
  Yes    26 1014
  <NA>    0   14


[[9]]
[[9]]$variable
[1] "family_mem_with_asd"

[[9]]$table

        No Yes
  No   800 131
  Yes  525 515
  <NA>   5   9


[[10]]
[[10]]$variable
[1] "asd_traits"

[[10]]$table

        No Yes
  No   585 346
  Yes  323 717
  <NA>   3  11

Every single patient with social_behavioural_issues == Yes has depression == Yes, and every patient with social_behavioural_issues == No has depression == No. Because these two columns contain identical information across all 1,970 complete cases, mice detected linear dependency and automatically dropped social_behavioural_issues.

speech_delay_language_disorder & learning_disorder: Whenever social_behavioural_issues == Yes, 100% of patients (1,040 / 1,040) also have Yes for these conditions. There are zero No cases.

Hence, social_behavioral_issues were dropped.

Let's check whether there is any possibility of MAR in social_behavioral issues.

In [ ]:
table(
  Respondent = asd_mice$who_completed_the_test,
  Missing_Social_Issues = is.na(asd_mice$social_behavioural_issues),
  useNA = "ifany"
)  # Checking for structural missingness; If all missing values are under one category, it means that that variable can explain
   # can explain the missigness. Hence, MAR possibility.

                          Missing_Social_Issues
Respondent                 FALSE TRUE
  Family Member              716    0
  Health Care Professional  1219   14
  Others                       3    0
  School And Ngo              29    0
  Self                         4    0

All missing Social behavioral issues are explained by the respondent group - Health Care Professional. So, possibility of MAR.

In [ ]:
# 2. Age Distribution across Missing vs. Observed groups
asd_mice |>
  group_by(Missing_Social_Issues = is.na(social_behavioural_issues)) |>
  summarise(
    Count = n(),
    Min_Age = min(age_years, na.rm = TRUE),
    Median_Age = median(age_years, na.rm = TRUE),
    Max_Age = max(age_years, na.rm = TRUE),
    Mean_Age = round(mean(age_years, na.rm = TRUE), 2)
  ) # Checking for structural missingness; If all missing values are under age group, it means that that variable can explain
   # can explain the missigness. Hence, MAR possibility.

  Missing_Social_Issues Count Min_Age Median_Age Max_Age Mean_Age
1 FALSE                 1971  1       9.0        18      9.62
2  TRUE                   14  3       8.5        17      9.79

Age distribution is same across both groups. Could be MCAR. Overall, till now, the results point to MAR wrt respondent & social behavioral issues and asd_traits & qchat10 at least. So, there is a possibility that it is not completely MNAR. Even the collinear variable in MICE shows the possiblity of MAR. So, relying on only complete cases might not be the best even if some other variables show the possibility of MCAR. MICE implementation was justified.

However, with social_behavioral_issues being highly explained by depression and also other variables, it would be wise to remove it.

And the different autism scores are meant for different age groups.

AQ10 is meant only for 16 and older.
CARS is meant for 2 and above.
SRS is meant for 4-18 year olds.
QChat10 is meant for 18-24 month olds.
So, the scores are not standardized.

Also, they could be highly correlated to ASD traits as they are used for the screening itself. So, dropping them would be better.

In [ ]:
asd_model <- asd_mice %>%
  select(
    -a1,
    -a2,
    -a3,
    -a4,
    -a5,
    -a6,
    -a7,
    -a8,
    -a9,
    -a10_autism_spectrum_quotient,
    -social_responsiveness_scale,
    -qchat_10_score,
    -childhood_autism_rating_scale,
    -social_behavioural_issues
  )

  asd_model

     case_no_patients age_years speech_delay_language_disorder
1     1               2         Yes
2     2               3         Yes
3     3               3         Yes
4     4               2         Yes
5     5               2         Yes
6     6               2         Yes
7     7               3         Yes
8     8               3         Yes
9     9               3         Yes
10   10               2         Yes
11   11               3         Yes
12   12               1         Yes
13   13               2         Yes
14   14               1         Yes
15   15               1         Yes
16   16               1         Yes
17   17               3         Yes
18   18               1         Yes
19   19               2         Yes
20   20               1         Yes
21   21               3         Yes
22   22               3         Yes
23   23               3         Yes
24   24               3         Yes
25   25               2         Yes
26   26               2         Yes
27   27               3         Yes
28   28               3         Yes
29   29               3         Yes
30   30               3         Yes
⋮    ⋮                ⋮         ⋮
1956 1956             14        No
1957 1957              7        No
1958 1958             14        No
1959 1959              7        No
1960 1960             14        No
1961 1961              7        No
1962 1962             14        No
1963 1963              7        No
1964 1964             14        No
1965 1965              5        No
1966 1966              4        No
1967 1967              7        No
1968 1968             14        No
1969 1969              7        No
1970 1970             14        No
1971 1971              7        No
1972 1972             14        No
1973 1973              7        No
1974 1974             14        No
1975 1975              7        No
1976 1976             14        No
1977 1977              7        No
1978 1978             14        No
1979 1979              7        No
1980 1980             14        No
1981 1981              7        No
1982 1982             14        No
1983 1983              7        No
1984 1984             14        No
1985 1985              7        No
     learning_disorder genetic_disorders depression
1    Yes               Yes               Yes
2    Yes               Yes               Yes
3    Yes               Yes               Yes
4    Yes               No                Yes
5    Yes               No                Yes
6    Yes               No                Yes
7    Yes               Yes               Yes
8    Yes               Yes               Yes
9    Yes               No                Yes
10   Yes               No                Yes
11   Yes               Yes               Yes
12   Yes               Yes               Yes
13   Yes               Yes               Yes
14   Yes               Yes               Yes
15   Yes               No                Yes
16   Yes               No                Yes
17   Yes               Yes               Yes
18   Yes               Yes               Yes
19   Yes               Yes               Yes
20   Yes               Yes               Yes
21   Yes               Yes               Yes
22   Yes               Yes               Yes
23   Yes               Yes               Yes
24   Yes               Yes               Yes
25   Yes               Yes               Yes
26   Yes               Yes               Yes
27   Yes               Yes               Yes
28   Yes               Yes               Yes
29   Yes               Yes               Yes
30   Yes               Yes               Yes
⋮    ⋮                 ⋮                 ⋮
1956 No                No                No
1957 No                No                No
1958 No                No                No
1959 No                No                No
1960 No                No                No
1961 No                No                No
1962 No                No                No
1963 No                No                No
1964 No                No                No
1965 No                No                No
1966 No                No                No
1967 No                No                No
1968 No                No                No
1969 No                No                No
1970 No                No                No
1971 No                No                No
1972 No                No                No
1973 No                No                No
1974 No                No                No
1975 No                No                No
1976 No                No                No
1977 No                No                No
1978 No                No                No
1979 No                No                No
1980 No                No                No
1981 No                No                No
1982 No                No                No
1983 No                No                No
1984 No                No                No
1985 No                No                No
     global_developmental_delay_intellectual_disability anxiety_disorder sex
1    Yes                                                Yes              F
2    Yes                                                Yes              M
3    Yes                                                Yes              M
4    Yes                                                Yes              M
5    Yes                                                Yes              F
6    Yes                                                Yes              M
7    Yes                                                Yes              M
8    Yes                                                Yes              M
9    Yes                                                Yes              M
10   Yes                                                Yes              M
11   Yes                                                Yes              M
12   Yes                                                Yes              M
13   Yes                                                Yes              F
14   Yes                                                Yes              F
15   Yes                                                Yes              M
16   Yes                                                Yes              M
17   Yes                                                Yes              M
18   Yes                                                Yes              F
19   Yes                                                Yes              F
20   Yes                                                Yes              M
21   Yes                                                Yes              M
22   Yes                                                Yes              M
23   Yes                                                Yes              M
24   Yes                                                Yes              M
25   Yes                                                Yes              M
26   Yes                                                Yes              M
27   Yes                                                Yes              M
28   Yes                                                Yes              M
29   Yes                                                Yes              M
30   Yes                                                Yes              M
⋮    ⋮                                                  ⋮                ⋮
1956 No                                                 No               M
1957 No                                                 No               F
1958 No                                                 No               M
1959 No                                                 No               M
1960 No                                                 No               M
1961 No                                                 No               M
1962 No                                                 No               M
1963 No                                                 No               F
1964 No                                                 No               F
1965 No                                                 No               M
1966 No                                                 No               M
1967 No                                                 No               M
1968 No                                                 No               F
1969 No                                                 No               F
1970 No                                                 No               M
1971 No                                                 No               M
1972 No                                                 No               F
1973 No                                                 No               M
1974 No                                                 No               M
1975 No                                                 No               M
1976 No                                                 No               M
1977 No                                                 No               M
1978 No                                                 No               F
1979 No                                                 No               F
1980 No                                                 No               M
1981 No                                                 No               M
1982 No                                                 No               F
1983 No                                                 No               M
1984 No                                                 No               M
1985 No                                                 No               M
     ethnicity      jaundice family_mem_with_asd who_completed_the_test
1    Middle Eastern Yes      No                  Family Member
2    White European Yes      No                  Family Member
3    Middle Eastern Yes      No                  Family Member
4    Hispanic       No       No                  Family Member
5    White European No       No                  Family Member
6    Black          No       No                  Family Member
7    Asian          Yes      No                  Family Member
8    Asian          Yes      No                  Family Member
9    Asian          No       No                  Family Member
10   South Asian    No       No                  Health Care Professional
11   Hispanic       Yes      Yes                 Family Member
12   Middle Eastern Yes      No                  Family Member
13   Middle Eastern Yes      No                  Family Member
14   Middle Eastern Yes      No                  Family Member
15   Middle Eastern Yes      No                  Family Member
16   Black          Yes      No                  Family Member
17   Middle Eastern Yes      Yes                 Family Member
18   Middle Eastern Yes      No                  Family Member
19   Middle Eastern Yes      No                  Family Member
20   Black          Yes      No                  Family Member
21   Middle Eastern Yes      No                  Family Member
22   Middle Eastern Yes      No                  Family Member
23   Native Indian  Yes      Yes                 Health Care Professional
24   Middle Eastern Yes      Yes                 Family Member
25   White European Yes      No                  Family Member
26   Middle Eastern Yes      No                  Family Member
27   Middle Eastern Yes      No                  Family Member
28   Others         Yes      No                  Family Member
29   Middle Eastern Yes      Yes                 Family Member
30   Middle Eastern Yes      No                  Family Member
⋮    ⋮              ⋮        ⋮                   ⋮
1956 Middle Eastern No       No                  Health Care Professional
1957 South Asian    No       No                  Health Care Professional
1958 White European No       No                  Health Care Professional
1959 Middle Eastern No       No                  Health Care Professional
1960 Asian          No       Yes                 Health Care Professional
1961 White European No       No                  Health Care Professional
1962 Middle Eastern No       No                  Health Care Professional
1963 South Asian    No       No                  Health Care Professional
1964 Asian          No       No                  Health Care Professional
1965 Asian          No       Yes                 Health Care Professional
1966 White European No       No                  Health Care Professional
1967 Middle Eastern No       No                  Health Care Professional
1968 South Asian    No       No                  Health Care Professional
1969 Asian          No       No                  Health Care Professional
1970 White European No       No                  Health Care Professional
1971 Middle Eastern No       No                  Health Care Professional
1972 South Asian    No       No                  Health Care Professional
1973 White European No       No                  Health Care Professional
1974 Middle Eastern No       No                  Health Care Professional
1975 Asian          No       Yes                 Health Care Professional
1976 White European No       No                  Health Care Professional
1977 Middle Eastern No       No                  Health Care Professional
1978 South Asian    No       No                  Health Care Professional
1979 Asian          No       No                  Health Care Professional
1980 White European No       No                  Health Care Professional
1981 Middle Eastern No       No                  Health Care Professional
1982 South Asian    No       No                  Health Care Professional
1983 White European No       No                  Health Care Professional
1984 Middle Eastern No       No                  Health Care Professional
1985 White European No       No                  Health Care Professional
     asd_traits
1    No
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    No
10   Yes
11   Yes
12   Yes
13   No
14   Yes
15   No
16   Yes
17   No
18   Yes
19   No
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   No
27   Yes
28   Yes
29   Yes
30   No
⋮    ⋮
1956 No
1957 No
1958 Yes
1959 No
1960 Yes
1961 Yes
1962 No
1963 No
1964 No
1965 Yes
1966 Yes
1967 No
1968 No
1969 No
1970 Yes
1971 No
1972 No
1973 Yes
1974 No
1975 Yes
1976 Yes
1977 No
1978 No
1979 No
1980 Yes
1981 No
1982 No
1983 Yes
1984 No
1985 Yes

In [ ]:
dim(asd_model)

[1] 1985   14

In [ ]:
colSums(is.na(asd_model))

                                  case_no_patients
                                                 0
                                         age_years
                                                 0
                    speech_delay_language_disorder
                                                 0
                                 learning_disorder
                                                 0
                                 genetic_disorders
                                                 0
                                        depression
                                                 1
global_developmental_delay_intellectual_disability
                                                 0
                                  anxiety_disorder
                                                 0
                                               sex
                                                 0
                                         ethnicity
                                                 0
                                          jaundice
                                                 0
                               family_mem_with_asd
                                                 0
                            who_completed_the_test
                                                 0
                                        asd_traits
                                                 0

Only one row has missing data with depression, so we drop it.

In [ ]:
asd_model_complete <- asd_model %>%
  tidyr::drop_na()

asd_model_complete

     case_no_patients age_years speech_delay_language_disorder
1     1               2         Yes
2     2               3         Yes
3     3               3         Yes
4     4               2         Yes
5     5               2         Yes
6     6               2         Yes
7     7               3         Yes
8     8               3         Yes
9     9               3         Yes
10   10               2         Yes
11   11               3         Yes
12   12               1         Yes
13   13               2         Yes
14   14               1         Yes
15   15               1         Yes
16   16               1         Yes
17   17               3         Yes
18   18               1         Yes
19   19               2         Yes
20   20               1         Yes
21   21               3         Yes
22   22               3         Yes
23   23               3         Yes
24   24               3         Yes
25   25               2         Yes
26   26               2         Yes
27   27               3         Yes
28   28               3         Yes
29   29               3         Yes
30   30               3         Yes
⋮    ⋮                ⋮         ⋮
1955 1956             14        No
1956 1957              7        No
1957 1958             14        No
1958 1959              7        No
1959 1960             14        No
1960 1961              7        No
1961 1962             14        No
1962 1963              7        No
1963 1964             14        No
1964 1965              5        No
1965 1966              4        No
1966 1967              7        No
1967 1968             14        No
1968 1969              7        No
1969 1970             14        No
1970 1971              7        No
1971 1972             14        No
1972 1973              7        No
1973 1974             14        No
1974 1975              7        No
1975 1976             14        No
1976 1977              7        No
1977 1978             14        No
1978 1979              7        No
1979 1980             14        No
1980 1981              7        No
1981 1982             14        No
1982 1983              7        No
1983 1984             14        No
1984 1985              7        No
     learning_disorder genetic_disorders depression
1    Yes               Yes               Yes
2    Yes               Yes               Yes
3    Yes               Yes               Yes
4    Yes               No                Yes
5    Yes               No                Yes
6    Yes               No                Yes
7    Yes               Yes               Yes
8    Yes               Yes               Yes
9    Yes               No                Yes
10   Yes               No                Yes
11   Yes               Yes               Yes
12   Yes               Yes               Yes
13   Yes               Yes               Yes
14   Yes               Yes               Yes
15   Yes               No                Yes
16   Yes               No                Yes
17   Yes               Yes               Yes
18   Yes               Yes               Yes
19   Yes               Yes               Yes
20   Yes               Yes               Yes
21   Yes               Yes               Yes
22   Yes               Yes               Yes
23   Yes               Yes               Yes
24   Yes               Yes               Yes
25   Yes               Yes               Yes
26   Yes               Yes               Yes
27   Yes               Yes               Yes
28   Yes               Yes               Yes
29   Yes               Yes               Yes
30   Yes               Yes               Yes
⋮    ⋮                 ⋮                 ⋮
1955 No                No                No
1956 No                No                No
1957 No                No                No
1958 No                No                No
1959 No                No                No
1960 No                No                No
1961 No                No                No
1962 No                No                No
1963 No                No                No
1964 No                No                No
1965 No                No                No
1966 No                No                No
1967 No                No                No
1968 No                No                No
1969 No                No                No
1970 No                No                No
1971 No                No                No
1972 No                No                No
1973 No                No                No
1974 No                No                No
1975 No                No                No
1976 No                No                No
1977 No                No                No
1978 No                No                No
1979 No                No                No
1980 No                No                No
1981 No                No                No
1982 No                No                No
1983 No                No                No
1984 No                No                No
     global_developmental_delay_intellectual_disability anxiety_disorder sex
1    Yes                                                Yes              F
2    Yes                                                Yes              M
3    Yes                                                Yes              M
4    Yes                                                Yes              M
5    Yes                                                Yes              F
6    Yes                                                Yes              M
7    Yes                                                Yes              M
8    Yes                                                Yes              M
9    Yes                                                Yes              M
10   Yes                                                Yes              M
11   Yes                                                Yes              M
12   Yes                                                Yes              M
13   Yes                                                Yes              F
14   Yes                                                Yes              F
15   Yes                                                Yes              M
16   Yes                                                Yes              M
17   Yes                                                Yes              M
18   Yes                                                Yes              F
19   Yes                                                Yes              F
20   Yes                                                Yes              M
21   Yes                                                Yes              M
22   Yes                                                Yes              M
23   Yes                                                Yes              M
24   Yes                                                Yes              M
25   Yes                                                Yes              M
26   Yes                                                Yes              M
27   Yes                                                Yes              M
28   Yes                                                Yes              M
29   Yes                                                Yes              M
30   Yes                                                Yes              M
⋮    ⋮                                                  ⋮                ⋮
1955 No                                                 No               M
1956 No                                                 No               F
1957 No                                                 No               M
1958 No                                                 No               M
1959 No                                                 No               M
1960 No                                                 No               M
1961 No                                                 No               M
1962 No                                                 No               F
1963 No                                                 No               F
1964 No                                                 No               M
1965 No                                                 No               M
1966 No                                                 No               M
1967 No                                                 No               F
1968 No                                                 No               F
1969 No                                                 No               M
1970 No                                                 No               M
1971 No                                                 No               F
1972 No                                                 No               M
1973 No                                                 No               M
1974 No                                                 No               M
1975 No                                                 No               M
1976 No                                                 No               M
1977 No                                                 No               F
1978 No                                                 No               F
1979 No                                                 No               M
1980 No                                                 No               M
1981 No                                                 No               F
1982 No                                                 No               M
1983 No                                                 No               M
1984 No                                                 No               M
     ethnicity      jaundice family_mem_with_asd who_completed_the_test
1    Middle Eastern Yes      No                  Family Member
2    White European Yes      No                  Family Member
3    Middle Eastern Yes      No                  Family Member
4    Hispanic       No       No                  Family Member
5    White European No       No                  Family Member
6    Black          No       No                  Family Member
7    Asian          Yes      No                  Family Member
8    Asian          Yes      No                  Family Member
9    Asian          No       No                  Family Member
10   South Asian    No       No                  Health Care Professional
11   Hispanic       Yes      Yes                 Family Member
12   Middle Eastern Yes      No                  Family Member
13   Middle Eastern Yes      No                  Family Member
14   Middle Eastern Yes      No                  Family Member
15   Middle Eastern Yes      No                  Family Member
16   Black          Yes      No                  Family Member
17   Middle Eastern Yes      Yes                 Family Member
18   Middle Eastern Yes      No                  Family Member
19   Middle Eastern Yes      No                  Family Member
20   Black          Yes      No                  Family Member
21   Middle Eastern Yes      No                  Family Member
22   Middle Eastern Yes      No                  Family Member
23   Native Indian  Yes      Yes                 Health Care Professional
24   Middle Eastern Yes      Yes                 Family Member
25   White European Yes      No                  Family Member
26   Middle Eastern Yes      No                  Family Member
27   Middle Eastern Yes      No                  Family Member
28   Others         Yes      No                  Family Member
29   Middle Eastern Yes      Yes                 Family Member
30   Middle Eastern Yes      No                  Family Member
⋮    ⋮              ⋮        ⋮                   ⋮
1955 Middle Eastern No       No                  Health Care Professional
1956 South Asian    No       No                  Health Care Professional
1957 White European No       No                  Health Care Professional
1958 Middle Eastern No       No                  Health Care Professional
1959 Asian          No       Yes                 Health Care Professional
1960 White European No       No                  Health Care Professional
1961 Middle Eastern No       No                  Health Care Professional
1962 South Asian    No       No                  Health Care Professional
1963 Asian          No       No                  Health Care Professional
1964 Asian          No       Yes                 Health Care Professional
1965 White European No       No                  Health Care Professional
1966 Middle Eastern No       No                  Health Care Professional
1967 South Asian    No       No                  Health Care Professional
1968 Asian          No       No                  Health Care Professional
1969 White European No       No                  Health Care Professional
1970 Middle Eastern No       No                  Health Care Professional
1971 South Asian    No       No                  Health Care Professional
1972 White European No       No                  Health Care Professional
1973 Middle Eastern No       No                  Health Care Professional
1974 Asian          No       Yes                 Health Care Professional
1975 White European No       No                  Health Care Professional
1976 Middle Eastern No       No                  Health Care Professional
1977 South Asian    No       No                  Health Care Professional
1978 Asian          No       No                  Health Care Professional
1979 White European No       No                  Health Care Professional
1980 Middle Eastern No       No                  Health Care Professional
1981 South Asian    No       No                  Health Care Professional
1982 White European No       No                  Health Care Professional
1983 Middle Eastern No       No                  Health Care Professional
1984 White European No       No                  Health Care Professional
     asd_traits
1    No
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    No
10   Yes
11   Yes
12   Yes
13   No
14   Yes
15   No
16   Yes
17   No
18   Yes
19   No
20   Yes
21   Yes
22   Yes
23   Yes
24   Yes
25   Yes
26   No
27   Yes
28   Yes
29   Yes
30   No
⋮    ⋮
1955 No
1956 No
1957 Yes
1958 No
1959 Yes
1960 Yes
1961 No
1962 No
1963 No
1964 Yes
1965 Yes
1966 No
1967 No
1968 No
1969 Yes
1970 No
1971 No
1972 Yes
1973 No
1974 Yes
1975 Yes
1976 No
1977 No
1978 No
1979 Yes
1980 No
1981 No
1982 Yes
1983 No
1984 Yes

In [ ]:
dim(asd_model_complete)

[1] 1984   14

In [ ]:
write.csv(asd_model_complete, "asd_model.csv", row.names = FALSE)